[env:pro_mini_3v3]
platform = atmelavr
board = pro8MHzatmega328
framework = arduino
monitor_speed = 115200

; Use shared protocol header
build_flags = -I../shared

; Auto-increment FW_VERSION before each build
extra_scripts = pre:increment_version.py
